name: Python autotests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

      

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5 
        with:
          python-version: 'pypy3.10' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: playwright install
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
      - name: Run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
    
  generate-report:
    runs-on: ubuntu-latest
    name: Generate report
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure_2.34.1.tgz && sudo tar -xvfz allure_2.34.1.tgz -C /opt/ && sudo ln -s /opt/allure_2.34.1/bin/allure usr/bin/allure 
 
  




